#!/usr/bin/python
#--- coding=utf-8 ------


basepath = "/home/pwn/mlfam_code"

arm_op = ["MOV","MVN","MRS","MSR","ADD","ADC","QADD","QDADD","SUB","SBC","RSB","RSC","QSUB","QDSUB","MUL","MLA","UMULL","UMLAL","\
SMULL","SMLAL","SMULxy","SMULWy","SMLAxy","SMLAWy","SMLALxy","CLZ","TST","TEQ","AND","EOR","ORR","BIC","NOP","CMP","CMN","FMSR","FMRS","\
FMDLR","FMRDL","FMDHR","FMRDH","FMXR","FMRX","FMSTAT","AND","EOR","ORR","TST","LSL","LSR","ASR","ROR","B","BL","BX","BLX","SWI","BKPT","LDR","LDRH","\
LDRB","LDRSH","LDRSB","LDMTA","STR","STRH","STRB","STMIA","PUSH","POP","LDM","STM","SWP","CDP","CDP2","MRC","MRC2","LDC","LDC2","STC","STC2","\
FMUL","FMULS","FMULD","FNMUL","FNMULS","FNMULD","FMAC","FMACS","FMACD","FNMAC","FNMACS","FNMACD","FMSC","FMSCS","FMSCD","\
FNMSC","FNMSCS","FNMSCD","FADD","FADDS","FADDD","FSUB","FSUBS","FSUBD","FDIV","DIV","FDIVS","FDIVD","FCPY","FCPYS","FCPYD","FABS","ABS","FABSS","\
FABSD","FNEG","FNEGS","FNEGD","FSQRT","FSQRTS","FSQRTD","FCMP","FCMPS","FCMPD","FCVTDS","FCVTSD","FUITO","FUITOS","FUITOD","FTOUI","FTOSI","FSITO","\
FSITOS","FSITOD","FST","FSTS","FSTD","FSTMIA","FSTMIAS","FSTMIAD","FSTMIAX","FSTMDB","FSTMDBS","FSTMDBD","FSTMDBX","FLD","FLDS","FLDD","\
FLDMIA","FLDMIAS","FLDMIAD","FLDMIAX","FLDMDB","FLDMDBS","FLDMDBD","FLDMDBX"]